source "https://supermarket.chef.io"
Encoding.default_external = Encoding::UTF_8
metadata

cookbook 'glassfish', '~> 0.7.6'
cookbook 'mysql', '~> 8.0.3'
cookbook 'java', '~> 1.42.0'
cookbook 'poise-python', '~> 1.5.1'
cookbook 'compat_resource', '= 12.13.38'
cookbook 'mongodb', '~> 0.16.2'
cookbook 'nodejs', '~> 2.4.4'
cookbook 'yum-epel', '~> 1.0.1'
cookbook 'yum-mysql-community', '~> 1.0.0'
